### ISSUE TITLE
Coordinate module checklist

### ISSUE THREAD

**Issue by burlingsmith** [cmarcbs7/chickenwire#17]
**Axial coordinates:**
- [ ] Conversions
  - [ ] MultiCoord
  - [ ] Cube
  - [ ] Double
  - [ ] Offset
  - [ ] From/To Tuple
  - [ ] From coordinates
- [ ] ORIGIN constant
- [ ] Neighbor(s)
- [ ] Diagonal(s)
- [ ] Distance
- [ ] Rotations
- [ ] Rings
- [ ] Spirals

**Cube coordinates:**
- [ ] Conversions
  - [ ] MultiCoord
  - [ ] Axial
  - [ ] Double
  - [ ] Offset
  - [ ] From/To Tuple
  - [x] From coordinates
- [x] ORIGIN constant
- [x] Neighbor(s)
- [x] Diagonal(s)
- [x] Distance
- [x] Rotations
- [x] Rings
- [x] Spirals

**Double coordinates:**
- [ ] Conversions
  - [ ] MultiCoord
  - [ ] Axial
  - [ ] Cube
  - [ ] Offset
  - [ ] From/To Tuple
  - [ ] From coordinates
- [ ] ORIGIN constant
- [ ] Neighbor(s)
- [ ] Diagonal(s)
- [ ] Distance
- [ ] Rotations
- [ ] Rings
- [ ] Spirals

**Offset coordinates:**
- [ ] Conversions
  - [ ] MultiCoord
  - [ ] Axial
  - [ ] Cube
  - [ ] Double
  - [ ] From/To Tuple
  - [ ] From coordinates
- [ ] ORIGIN constant
- [ ] Neighbor(s)
- [ ] Diagonal(s)
- [ ] Distance
- [ ] Rotations
- [ ] Rings
- [ ] Spirals

**Multi-coordinates:**
- [ ] Conversions
  - [ ] Axial
  - [ ] Cube
  - [ ] Double
  - [ ] Offset
  - [ ] From/To Tuple
  - [ ] From coordinates
- [ ] ORIGIN constant
- [ ] Neighbor(s)
- [ ] Diagonal(s)
- [ ] Distance
- [ ] Rotations
- [ ] Rings
- [ ] Spirals
